# Generated by Django 5.2.1 on 2025-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Когда была создана')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Нужна доставка')),
                ('delivery_address', models.CharField(max_length=215, null=True, verbose_name='Адресс доставки')),
                ('pickup_point', models.CharField(blank=True, max_length=250, null=True, verbose_name='Откукда нужно забрать')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Оплата при получении'), ('online_payment', 'Онлайн оплата')], default='online_payment', max_length=50, verbose_name='Метод оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено ли')),
                ('status', models.CharField(default='pending', verbose_name='Статус Продукта')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
