# Generated by Django 5.2.1 on 2025-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_logs/', verbose_name='Профиль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['email', 'code'], name='user_app_sm_email_ba36c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_app_us_email_eb2b78_idx'),
        ),
    ]
