# Generated by Django 5.2.1 on 2025-05-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts_app', '0001_initial'),
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.product', verbose_name='Товар/Продукт'),
        ),
    ]
