# Generated by Django 5.2.1 on 2025-06-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество товаров')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_id', models.CharField(max_length=100, unique=True, verbose_name='ID транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Оплата при получении'), ('online_payment', 'Онлайн оплата')], default='online_payment', max_length=50, verbose_name='Метод оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено ли')),
                ('status', models.CharField(default='pending', verbose_name='Статус Продукта')),
                ('transition_error', models.TextField(blank=True, null=True, verbose_name='ОШибка Транзакции')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='USD', max_length=3, verbose_name=' Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.order', verbose_name='Заказ')),
            ],
        ),
    ]
