# Generated by Django 5.2.1 on 2025-05-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods_app', '0002_initial'),
        ('payment_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто оплатил'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.payment', verbose_name='Платеж'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.product', verbose_name='За какой товар оплачено'),
        ),
    ]
