# Generated by Django 5.2.1 on 2025-06-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя Атрибута')),
                ('type_attribute', models.CharField(max_length=100, verbose_name=' Тип Атрибута')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25, verbose_name='url')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='Brand_logo/', verbose_name='Лого Бренда')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25, verbose_name='url')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('image', models.ImageField(upload_to='Category_images/', verbose_name='Изображение категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25, verbose_name='url')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name=' На продаже')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество товаров')),
                ('discount_price', models.BooleanField(default=False, verbose_name=' Скидка на Продукт')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='Product_images/', verbose_name='Изображение категории')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение продукта')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарии')),
                ('image', models.ImageField(upload_to='Product_Review_images/', verbose_name='Изобаржение продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_app.product')),
            ],
        ),
    ]
