# Generated by Django 5.2.1 on 2025-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type_attribute',
            field=models.CharField(max_length=100, verbose_name=' Тип Атрибута'),
        ),
    ]
