# Generated by Django 5.2.1 on 2025-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Brand_logo/', verbose_name='Лого Бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Category_images/', verbose_name='Изображение категории'),
        ),
    ]
